---
name: Release qnapexporter

on:  # yamllint disable-line rule:truthy
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: self-hosted
    permissions:
      contents: write  # for wangyoucao577/go-release-action to upload assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wangyoucao577/go-release-action@v1.35
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          build_command: make build PACKAGE_VERSION="$GITHUB_REF_NAME"
          binary_name: bin/qnapexporter
          asset_name: qnapexporter
          overwrite: true
